# Generated by Django 5.0.6 on 2024-07-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_produto_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preço_compra',
            new_name='preco_compra',
        ),
    ]
