# Generated by Django 5.0.6 on 2024-07-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_imagens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagens',
            new_name='Imagem',
        ),
    ]
