# Generated by Django 5.0.6 on 2024-07-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_corgo_users_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cargo',
            field=models.CharField(choices=[('V', 'Vendedor'), ('G', 'Gerente'), ('C', 'Caixa')], max_length=1),
        ),
    ]
